apiVersion: v1
kind: ConfigMap
metadata:
  name: relayer-config
  labels:
    app: relayer
data:
  CORE_CONTRACT_ADDRESS: ""
  CHAIN_RPC_PROVIDER: ""
  CHAIN_ID: ""
  FEE_PER_GAS: ""
  RELAYER_EMAIL_ADDR: ""
  RELAYER_HOSTNAME: ""
  WEB_SERVER_ADDRESS: ""
  SUBGRAPH_URL: ""
  CIRCUITS_DIR_PATH: ""
  INPUT_FILES_DIR_PATH: ""
  EMAIL_TEMPLATES_PATH: ""
  ONBOARDING_TOKEN_ADDR: ""
  ONBOARDING_TOKEN_AMOUNT: ""
  ONBOARDING_TOKEN_DISTRIBUTION_LIMIT: ""
  ONBOARDING_REPLY: ""
  CANISTER_ID: ""
  IC_REPLICA_URL: ""
  JSON_LOGGER: ""
  DEMO_NFT_ADDR: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: relayer-secret
  labels:
    app: relayer
type: Opaque
data:
  PRIVATE_KEY:
  IMAP_DOMAIN_NAME:
  IMAP_PORT:
  SMTP_DOMAIN_NAME:
  LOGIN_ID:
  LOGIN_PASSWORD:
  PROVER_ADDRESS:
  PEM_PATH:

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: relayer
  labels:
    app: relayer
spec:
  replicas: 2 # Number of initial replicas
  selector:
    matchLabels:
      app: relayer
  template:
    metadata:
      labels:
        app: relayer
    spec:
      containers:
        - name: relayer-container
          image: bisht13/relayer:latest
          ports:
            - containerPort: 4500
          envFrom:
            - configMapRef:
                name: relayer-config
            - secretRef:
                name: relayer-secret
          resources:
            requests:
              memory: "8Gi"
              cpu: 4
            limits:
              memory: "16Gi"
              cpu: 8

---
apiVersion: v1
kind: Service
metadata:
  name: relayer-svc
spec:
  selector:
    app: relayer
  ports:
    - protocol: TCP
      port: 4500
      targetPort: 4500
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: relayer-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: relayer
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
